import Head from 'next/head'
import UserView from '../components/user'
import { wrapper } from '../redux/store'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Образец redux для nextjs от <a href='https://t.me/atom_baytovich'> AtomBaytovich </a>. Version 0.1</h1>
        <UserView/>
        <a style={{marginTop: 10}} href='https://github.com/kirill-konshin/next-redux-wrapper'>Документация к next-rediux-wrapper</a>
      </main>
    </div>
  )
}

// SSR and redux (полные прмиеры смотри в док-ции)
// staticProps: https://github.com/kirill-konshin/next-redux-wrapper#getstaticprops
// SSR: https://github.com/kirill-konshin/next-redux-wrapper#getserversideprops
// initialProps: https://github.com/kirill-konshin/next-redux-wrapper#pagegetinitialprops
export const getServerSideProps = wrapper.getServerSideProps((context) => 
  async ({ req, res, query }) => {
    const { dispatch } = context;
    // диспатчим данные
    await dispatch({
      type: 'SET_USER',
      payload: {
        count: 12345,
        firstName: 'Atom',
        lastName: 'Baytovich'
      }
    })

    return {
      props: {}
    }
  }
)
  